name: test screen print
on:
  workflow_dispatch

jobs:
  screen_capture:
    runs-on: ubuntu-latest
    container:
      image: maif/otoroshi:1.5.0-alpha.2
    steps:
      - uses: actions/checkout@v2.2.0
      # setup java to use sbt
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      # install node 14
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: screenshots-ci-action
        uses: flameddd/screenshots-ci-action@v1.1.1
        with:
          url: https://github.com
          fullPage: true
      - uses: actions/upload-artifact@v2
        with:
          path: screenshots
          name: Download-screenshots
      - name: Commit formatted sources
        run: |
          git config --local user.email "screenshot-github-actions@users.noreply.github.com"
          git config --local user.name "screenshot-github-actions"
          git add --all
          git commit -am "new screenshot from action"
      - name: Push formatted sources
        uses: ad-m/github-push-action@master
        with:
          branch: master
          github_token: ${{ secrets.GITHUB_TOKEN}}          
